export const demoInventoryItems = [
  { id: "inv-001", name: "Beer", quantity: 50, unit: "bottle", category: "Beverages" },
  { id: "inv-002", name: "Special Beer", quantity: 40, unit: "bottle", category: "Beverages" },
  { id: "inv-003", name: "Soft Drink / Ambo Water", quantity: 100, unit: "bottle", category: "Beverages" },
  { id: "inv-004", name: "Tekshino", quantity: 20, unit: "bottle", category: "Beverages" },
  { id: "inv-005", name: "Acacia White Wine", quantity: 15, unit: "bottle", category: "Beverages" },
  { id: "inv-006", name: "Acacia Red Wine", quantity: 15, unit: "bottle", category: "Beverages" },
  { id: "inv-007", name: "Rift Valley Wine", quantity: 12, unit: "bottle", category: "Beverages" },
  { id: "inv-008", name: "Areke", quantity: 30, unit: "shot", category: "Beverages" },
  { id: "inv-009", name: "Draft Beer", quantity: 60, unit: "glass", category: "Beverages" },
  { id: "inv-010", name: "Jack Master", quantity: 20, unit: "shot", category: "Beverages" },
  { id: "inv-011", name: "Foreign Liquor", quantity: 20, unit: "shot", category: "Beverages" },
  { id: "inv-012", name: "Amarula", quantity: 15, unit: "shot", category: "Beverages" },
  { id: "inv-013", name: "Red Bull", quantity: 30, unit: "can", category: "Beverages" },
  { id: "inv-014", name: "Tequila", quantity: 15, unit: "shot", category: "Beverages" },
  { id: "inv-015", name: "Sambuca", quantity: 15, unit: "shot", category: "Beverages" },
  { id: "inv-016", name: "Soft Drinks", quantity: 100, unit: "bottle", category: "Beverages" },
  { id: "inv-017", name: "Amarula Double", quantity: 10, unit: "double", category: "Beverages" },
];
