import { readDemoJSON, writeDemoJSON } from "@/lib/demo-storage";

export const demoCategories = [
  { id: "yetsom", name: "የጾም (Yetsom)", sortOrder: 0, isActive: true },
  { id: "yetsom-asa", name: "ዓሳ (Fish)", sortOrder: 1, parentId: "yetsom", isActive: true },
  { id: "yefsig", name: "የፍስግ (Yefsig)", sortOrder: 2, isActive: true },
  { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)", sortOrder: 3, parentId: "yefsig", isActive: true },
  { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)", sortOrder: 4, parentId: "yefsig", isActive: true },
  { id: "drinks", name: "Drinks", sortOrder: 5, isActive: true },
];

// Butcher required menu items (must go to butcher first)
export const BUTCHER_REQUIRED_ITEMS = ["Tibs", "Kurt", "Dulet", "Tere Sega", "Gored Gored"];

export const demoItems = [
  // YEFSIG-MAIN items (ምሳ & እራት - Lunch & Dinner combined)
  { id: "item-1", name: "Kurt (ቁርጥ)", price: 350, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Fresh raw beef cubes seasoned with mitmita and niter kibbeh — our signature dish", isAvailable: true, preparationTime: 8, variants: [], extras: [], image: "/images/kurt.jpg", requiresButcher: true },
  { id: "item-2", name: "Kitfo (ክትፎ)", price: 300, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Minced raw beef marinated in mitmita, niter kibbeh and cardamom", isAvailable: true, preparationTime: 8, variants: [], extras: [], image: "/images/kifo.jpg", requiresButcher: true },
  { id: "item-3", name: "Gored Gored (ጎረድ ጎረድ)", price: 320, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Large cubes of raw beef served with awaze dipping sauce", isAvailable: true, preparationTime: 8, variants: [], extras: [], image: "/images/gored gored.jpg", requiresButcher: true },
  { id: "item-4", name: "Tere Sega (ጠረ ስጋ)", price: 400, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Thinly sliced raw beef strips seasoned with traditional spices", isAvailable: true, preparationTime: 5, variants: [], extras: [], image: "/images/zilzil tibs.jpg", requiresButcher: true },
  { id: "item-9", name: "Dulet (ዱለት)", price: 200, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Minced tripe, liver and beef sautéed with onions and mitmita", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yefseg/kurs/ዱለት (Dulet).jpg", requiresButcher: true },
  { id: "item-10", name: "Lamb Tibs", price: 350, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Tender lamb cubes sautéed with rosemary and garlic", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/tibs.jpg", requiresButcher: true },
  { id: "item-48", name: "Yeheb Gorrod (የሀብ ጎረድ)", price: 380, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Grilled lamb ribs seasoned with Ethiopian spices", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/gored gored.jpg" },
  { id: "item-23", name: "Sambusa (ሳምቡሳ)", price: 100, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Crispy pastry filled with spiced minced meat — 3 pieces", isAvailable: true, preparationTime: 12, variants: [], extras: [] },
  { id: "item-5", name: "Tibs (ጥብስ)", price: 280, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Sautéed beef with onions, jalapeños, tomatoes and rosemary", isAvailable: true, preparationTime: 18, variants: [], extras: [], image: "/images/tibs.jpg", requiresButcher: true },
  { id: "item-6", name: "Awaze Tibs (አዋዜ ጥብስ)", price: 300, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef tibs simmered in spicy awaze sauce", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Awaze Tibs.jpg", requiresButcher: true },
  { id: "item-7", name: "Zilzil Tibs (ዝልዝል ጥብስ)", price: 320, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Thinly sliced beef strips sautéed with garlic and peppers", isAvailable: true, preparationTime: 18, variants: [], extras: [], image: "/images/zilzil tibs.jpg", requiresButcher: true },
  { id: "item-8", name: "Shekla Tibs (ሸክላ ጥብስ)", price: 380, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef tibs served sizzling in a traditional clay pot", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-52", name: "Beyaynetu (በያይነቱ)", price: 500, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Ethiopian combination platter — sample of tibs, kitfo, doro wat and vegetarian dishes", isAvailable: true, preparationTime: 30, variants: [], extras: [], image: "/images/Yetsom/በያይነቱ (Beyaynetu ).webp" },
  { id: "item-12", name: "Doro Wat (ዶሮ ወጥ)", price: 250, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Spicy chicken stew slow-cooked with berbere, served with hard-boiled egg", isAvailable: true, preparationTime: 35, variants: [], extras: [] },
  { id: "item-13", name: "Kai Wat (ቀይ ወጥ)", price: 220, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Rich spicy beef stew with berbere and niter kibbeh", isAvailable: true, preparationTime: 30, variants: [], extras: [] },
  { id: "item-14", name: "Minchet Abish (ምንጬ አብሽ)", price: 200, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Minced beef stew simmered with berbere and seasoned butter", isAvailable: true, preparationTime: 25, variants: [], extras: [] },
  { id: "item-15", name: "Alicha Wat (አሊጫ ወጥ)", price: 200, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Mild turmeric-based beef or lamb stew with potatoes and carrots", isAvailable: true, preparationTime: 25, variants: [], extras: [] },
  { id: "item-16", name: "Sega Wat (ሥጋ ወጥ)", price: 260, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Hearty lamb or beef chunks in traditional spiced sauce", isAvailable: true, preparationTime: 35, variants: [], extras: [] },
  { id: "item-17", name: "Gomen Besega (ጎመን በሥጋ)", price: 220, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Collard greens cooked with beef chunks and spices", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yetsom/ጎመን ጥብስ (Gomen Tibs).jpg" },
  { id: "item-49", name: "Beg Wat (በግ ወጥ)", price: 280, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Slow-cooked lamb stew in rich berbere sauce", isAvailable: true, preparationTime: 35, variants: [], extras: [] },
  { id: "item-28", name: "Enkulal Firfir (እንቁላል ፍርፍር)", price: 150, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Shredded injera with scrambled eggs and berbere sauce", isAvailable: true, preparationTime: 10, variants: [], extras: [] },
  { id: "item-50", name: "Dorho Fitfit (ዶሮ ፍትፍት)", price: 180, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Shredded injera with chicken and berbere sauce", isAvailable: true, preparationTime: 12, variants: [], extras: [] },
  
  // Goat Meat items (የፍየል ሥጋ)
  { id: "item-126", name: "ቅቅል የፍየል (Goat Meat Soup - Kikil)", price: 700, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Meat Soup (Kikil)", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/kekel.jpg", requiresButcher: true },
  { id: "item-127", name: "የፍየል ቁርጥ / ሸክላ ጥብስ 1/4 ኪሎ (Goat Qurt / Shekla Tibs 1/4 kg)", price: 1250, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Qurt (Raw) / Shekla Tibs 1/4 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-128", name: "የፍየል ቁርጥ / ሸክላ ጥብስ 1/2 ኪሎ (Goat Qurt / Shekla Tibs 1/2 kg)", price: 2500, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Qurt (Raw) / Shekla Tibs 1/2 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-129", name: "የፍየል ቁርጥ / ሸክላ ጥብስ 1 ኪሎ (Goat Qurt / Shekla Tibs 1 kg)", price: 5000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Qurt (Raw) / Shekla Tibs 1 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-130", name: "የፍየል አላንዶ 1/4 ኪሎ (Goat Meat Alando 1/4 kg)", price: 1500, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Meat Alando 1/4 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  { id: "item-131", name: "የፍየል አላንዶ 1/2 ኪሎ (Goat Meat Alando 1/2 kg)", price: 3000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Meat Alando 1/2 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  { id: "item-132", name: "የፍየል አላንዶ 1 ኪሎ (Goat Meat Alando 1 kg)", price: 6000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Goat Meat Alando 1 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  
  // Beef items (የበሬ ሥጋ)
  { id: "item-133", name: "የበሬ ቁርጥ / ሸክላ ጥብስ 1/4 ኪሎ (Beef Qurt / Shekla Tibs 1/4 kg)", price: 1000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Qurt (Raw) / Shekla Tibs 1/4 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-134", name: "የበሬ ቁርጥ / ሸክላ ጥብስ 1/2 ኪሎ (Beef Qurt / Shekla Tibs 1/2 kg)", price: 2000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Qurt (Raw) / Shekla Tibs 1/2 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-135", name: "የበሬ ቁርጥ / ሸክላ ጥብስ 1 ኪሎ (Beef Qurt / Shekla Tibs 1 kg)", price: 4000, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Qurt (Raw) / Shekla Tibs 1 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/shekla.jpg", requiresButcher: true },
  { id: "item-136", name: "የበሬ አላንዶ 1/4 ኪሎ (Beef Alando 1/4 kg)", price: 1200, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Alando 1/4 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  { id: "item-137", name: "የበሬ አላንዶ 1/2 ኪሎ (Beef Alando 1/2 kg)", price: 2250, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Alando 1/2 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  { id: "item-138", name: "የበሬ አላንዶ 1 ኪሎ (Beef Alando 1 kg)", price: 4500, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Alando 1 kg", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yefseg/Lunch and dinner/olando.jpg", requiresButcher: true },
  { id: "item-139", name: "የበሬ ጎርድ ጎርድ 1/4 ኪሎ (Beef Gored Gored 1/4 kg)", price: 1150, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Gored Gored 1/4 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/gored gored.jpg", requiresButcher: true },
  { id: "item-140", name: "የበሬ ጎርድ ጎርድ 1/2 ኪሎ (Beef Gored Gored 1/2 kg)", price: 2200, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Gored Gored 1/2 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/gored gored.jpg", requiresButcher: true },
  { id: "item-141", name: "የበሬ ጎርድ ጎርድ 1 ኪሎ (Beef Gored Gored 1 kg)", price: 4500, categoryId: "yefsig-main", category: { id: "yefsig-main", name: "ምሳ & እራት (Lunch & Dinner)" }, description: "Beef Gored Gored 1 kg", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/gored gored.jpg", requiresButcher: true },
  { id: "item-18", name: "Shiro (ሽሮ)", price: 150, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Smooth chickpea or lentil stew slow-cooked with berbere", isAvailable: true, preparationTime: 20, variants: [], extras: [] },
  { id: "item-19", name: "Misir Wat (ምስር ወጥ)", price: 150, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Red lentil stew in spicy berbere sauce", isAvailable: true, preparationTime: 22, variants: [], extras: [] },
  { id: "item-20", name: "Atkilt Wat (አትክልት ወጥ)", price: 130, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Mixed vegetable stew with carrots, potatoes and green beans", isAvailable: true, preparationTime: 18, variants: [], extras: [] },
  { id: "item-21", name: "Gomen (ጎመን)", price: 120, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Sautéed collard greens with garlic and ginger", isAvailable: true, preparationTime: 15, variants: [], extras: [] },
  { id: "item-22", name: "Buticha (ቡቲቻ)", price: 120, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Chickpea salad with lemon, onions and green peppers", isAvailable: true, preparationTime: 8, variants: [], extras: [] },
  { id: "item-53", name: "Timatim Fitfit (ቲማቲም ፍትፍት)", price: 130, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Shredded injera with fresh tomatoes, onions and lemon dressing", isAvailable: true, preparationTime: 8, variants: [], extras: [] },
  { id: "item-54", name: "Fosolia (ፎሶሊያ)", price: 120, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Green beans and carrots sautéed with onions and garlic", isAvailable: true, preparationTime: 15, variants: [], extras: [] },
  { id: "item-55", name: "Tikil Gomen (ጥቅል ጎመን)", price: 120, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Sautéed cabbage, carrots and potatoes with turmeric", isAvailable: true, preparationTime: 18, variants: [], extras: [] },
  { id: "item-56", name: "Dinich Wat (ድንች ወጥ)", price: 150, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Potato stew in mild spiced sauce", isAvailable: true, preparationTime: 22, variants: [], extras: [] },
  { id: "item-24", name: "Lentil Sambusa", price: 80, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Crispy pastry filled with spiced red lentils — 3 pieces", isAvailable: true, preparationTime: 12, variants: [], extras: [] },
  { id: "item-25", name: "Kolo (ቆሎ)", price: 60, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Roasted barley with peanuts and spices", isAvailable: true, preparationTime: 3, variants: [], extras: [] },
  { id: "item-26", name: "Injera (extra)", price: 30, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Extra injera on the side", isAvailable: true, preparationTime: 2, variants: [], extras: [] },
  { id: "item-27", name: "Dabo (ዳቦ)", price: 50, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Traditional Ethiopian bread baked in a clay oven", isAvailable: true, preparationTime: 5, variants: [], extras: [] },
  { id: "item-45", name: "Chechebsa (ጨጨብሳ)", price: 130, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Shredded flatbread sautéed in spiced butter and berbere", isAvailable: true, preparationTime: 12, variants: [], extras: [] },
  { id: "item-46", name: "Genfo (ገንፎ)", price: 100, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Thick roasted barley porridge served with niter kibbeh and berbere", isAvailable: true, preparationTime: 15, variants: [], extras: [] },
  { id: "item-47", name: "Kicha (ቅቻ)", price: 80, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Ethiopian-style flatbread baked on a griddle", isAvailable: true, preparationTime: 10, variants: [], extras: [] },
  
  // YETSOM-ASA items (fish)
  { id: "item-11", name: "Asa Tibs (ዓሣ ጥብስ)", price: 280, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Pan-fried tilapia with onions, tomatoes and herbs", isAvailable: true, preparationTime: 18, variants: [], extras: [] },
  { id: "item-57", name: "Asa Wat (ዓሣ ወጥ)", price: 250, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Fish simmered in spicy berbere sauce", isAvailable: true, preparationTime: 25, variants: [], extras: [] },
  { id: "item-58", name: "Gulash Asa (ጉላሽ ዓሣ)", price: 300, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Whole fried fish seasoned with Ethiopian spices", isAvailable: true, preparationTime: 20, variants: [], extras: [] },
  { id: "item-59", name: "Asa Dulet (ዓሣ ዱለት)", price: 220, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Flaked fish sautéed with onions, peppers and herbs", isAvailable: true, preparationTime: 15, variants: [], extras: [] },
  { id: "item-60", name: "Fish Goulash", price: 280, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Fish fillet in rich tomato and herb sauce", isAvailable: true, preparationTime: 22, variants: [], extras: [] },
  
  // Desserts & Beverages (default to YETSOM)
  { id: "item-29", name: "Firfir (ፍርፍር)", price: 250, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Shredded injera tossed in spicy berbere sauce", isAvailable: true, preparationTime: 10, variants: [], extras: [], image: "/images/Yetsom/Firfir.jpg" },
  { id: "item-30", name: "Atayef (አታይፍ)", price: 150, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Stuffed pancakes with cream, nuts and sweet syrup", isAvailable: true, preparationTime: 15, variants: [], extras: [] },
  { id: "item-31", name: "Ethiopian Cheesecake", price: 180, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Creamy cheesecake with a touch of honey and cardamom", isAvailable: true, preparationTime: 10, variants: [], extras: [] },
  { id: "item-32", name: "Halwa", price: 100, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Traditional sesame-based sweet with cardamom", isAvailable: true, preparationTime: 3, variants: [], extras: [] },
  { id: "item-110", name: "ቢራ (Beer)", price: 120, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Beer", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/beer.jpg" },
  { id: "item-111", name: "ስፔሻል ቢራ (Special Beer)", price: 140, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Special Beer", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/special beer.jpg" },
  { id: "item-112", name: "ለስላሳ / አምቦ ውሃ 1 ሊትር (Soft Drink / Ambo Water 1 Liter)", price: 80, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Soft Drink / Ambo Water 1 Liter", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Ambo Mineral Water (20 per box).jpg" },
  { id: "item-113", name: "ተክሽኖ (Tekshino)", price: 1000, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Tekshino (Wine/Liquor)", isAvailable: true, preparationTime: 3, variants: [], extras: [], image: "/images/Drinks/tekeshno.jpg" },
  { id: "item-114", name: "አካሺያ ነጭ ወይን (Acacia White Wine)", price: 2200, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Acacia White Wine", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/acacia white wine.jpg" },
  { id: "item-115", name: "አካሺያ ወይን (ቀይ) (Acacia Wine Red)", price: 2000, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Acacia Wine (Red)", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/acacia wine.jpg" },
  { id: "item-116", name: "ሪፍት ቫሊ (Rift Valley Wine)", price: 2000, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Rift Valley Wine", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/Rift valley.jpg" },
  { id: "item-117", name: "አረቄ በመልኪያ (Areke per Shot)", price: 100, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Areke (Local Spirit) per Shot", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Arake bemelekiya.jpg" },
  { id: "item-118", name: "ድራፍት ሲንግል (Draft Beer Single)", price: 65, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Draft Beer (Single)", isAvailable: true, preparationTime: 2, variants: [], extras: [], image: "/images/Drinks/single beer.jpg" },
  { id: "item-119", name: "ጃክ ማስተር ሾት (Jack Master Shot)", price: 450, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Jack Master Shot", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Rift valley.jpg" },
  { id: "item-120", name: "ፈረንጅ ሾት (Foreign Liquor Shot)", price: 500, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Foreign Liquor Shot", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Rift valley.jpg" },
  { id: "item-121", name: "አማሩላ ደብል (Amarula Double)", price: 800, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Amarula Double", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/amarula.jpg" },
  { id: "item-122", name: "ሬድቡል (Red Bull)", price: 900, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Red Bull", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Red bull.jpg" },
  { id: "item-123", name: "ቴኪላ ሾት (Tequila Shot)", price: 500, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Tequila Shot", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Tekila shot.jpg" },
  { id: "item-124", name: "ሳምቡካ ሾት (Sambuca Shot)", price: 500, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Sambuca Shot", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/Rift valley.jpg" },
  { id: "item-125", name: "ለስላሳ (Soft Drinks)", price: 80, categoryId: "drinks", category: { id: "drinks", name: "Drinks" }, description: "Soft drinks", isAvailable: true, preparationTime: 1, variants: [], extras: [], image: "/images/Drinks/soft drinks.jpg" },

  // Custom Yetsom items
  { id: "item-61", name: "Pasta batkilt (ፓስታ በአትክልት)", price: 300, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Pasta with mixed vegetables in traditional sauce", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yetsom/ፓስታ በአትክልት (Pasta batkilt).jpg" },
  { id: "item-62", name: "Pasta be Sego (ፓስታ በሰጎ)", price: 280, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Pasta served with traditional sego sauce", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yetsom/ፓስታ በሰጎ (Pasta be Sego).jpg" },
  { id: "item-63", name: "Gomen Tibs (ጎመን ጥብስ)", price: 400, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Sautéed collard greens with onions, garlic and peppers", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yetsom/ጎመን ጥብስ (Gomen Tibs).jpg" },
  { id: "item-64", name: "Gomen Kitfo (ጎመን ክትፎ)", price: 500, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Minced collard greens with traditional spices", isAvailable: true, preparationTime: 12, variants: [], extras: [], image: "/images/Yetsom/ጎመን ክትፎ (Gomen Kitfo).jpg" },
  { id: "item-65", name: "Telba (ተልባ)", price: 200, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Nutritious flaxseed porridge with spices", isAvailable: true, preparationTime: 10, variants: [], extras: [], image: "/images/Yetsom/ተልባ (Telba).jpg" },
  { id: "item-66", name: "Shiro Tegabino (ሽሮ ተጋቢኖ)", price: 300, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Rich chickpea stew with special spices", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yetsom/ሽሮ ተጋቢኖ (Shiro Tegabino).jpg" },
  { id: "item-67", name: "Suf (ሱፍ)", price: 250, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Traditional Ethiopian snack", isAvailable: true, preparationTime: 3, variants: [], extras: [], image: "/images/Yetsom/ሱፍ (Suf ).jpg" },
  { id: "item-68", name: "Timatim lebleb", price: 300, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Fresh tomato dish with lebleb spices", isAvailable: true, preparationTime: 8, variants: [], extras: [], image: "/images/Yetsom/timatim lebleb.jpg" },
  { id: "item-69", name: "Timatim katelo", price: 300, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Fresh tomato and vegetable salad", isAvailable: true, preparationTime: 8, variants: [], extras: [], image: "/images/Yetsom/timatim katelo.jpg" },
  { id: "item-70", name: "Special firfir (ስፔሻል ፍርፍር)", price: 300, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Special shredded injera with berbere sauce and spices", isAvailable: true, preparationTime: 10, variants: [], extras: [], image: "/images/Yetsom/Special firfir.jpg" },
  { id: "item-71", name: "Siro feses (ሽሮ ፈሰስ)", price: 250, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Thin shiro stew poured over injera", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yetsom/siro feses.jpg" },
  { id: "item-72", name: "Beyaynetu (በያይነቱ)", price: 400, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Vegetarian combination platter with assorted dishes on injera", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yetsom/በያይነቱ (Beyaynetu ).webp" },
  { id: "item-79", name: "Special Shiro (ስፔሻል ሽሮ)", price: 400, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Premium chickpea stew with extra spices and niter kibbeh", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yetsom/ስፔሻል ሽሮ (Special Shiro).jpg" },
  { id: "item-80", name: "Agegel half (አገግል ግማሽ)", price: 5000, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Half portion of agegel prepared with traditional spices", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yetsom/Agelgel.jpg" },
  { id: "item-81", name: "Agegel full (አገግል ሙሉ)", price: 900, categoryId: "yetsom", category: { id: "yetsom", name: "የጾም (Yetsom)" }, description: "Full portion of agegel prepared with traditional spices", isAvailable: true, preparationTime: 30, variants: [], extras: [], image: "/images/Yetsom/Agelgel.jpg" },

  // Breakfast items (ቁርስ)
  { id: "item-82", name: "Kuanta Firfir (ቋንጣ ፍርፍር)", price: 500, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Shredded injera with kuanta (dried beef) and berbere sauce", isAvailable: true, preparationTime: 10, variants: [], extras: [], image: "/images/Yefseg/kurs/ቋንጣ ፍርፍር (Kuanta Firfir).jpg" },
  { id: "item-83", name: "Sega Firfir (ሥጋ ፍርፍር)", price: 450, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Shredded injera with minced meat and berbere sauce", isAvailable: true, preparationTime: 10, variants: [], extras: [], image: "/images/Yefseg/kurs/ሥጋ ፍርፍር (Sega Firfir).jpg" },
  { id: "item-84", name: "Dulet (ዱለት)", price: 400, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Minced tripe, liver and beef sautéed with onions and mitmita", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yefseg/kurs/ዱለት (Dulet).jpg" },
  { id: "item-85", name: "Special Dulet (ስፔሻል ዱለት)", price: 600, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Premium dulet with extra spices and niter kibbeh", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yefseg/kurs/ስፔሻል ዱለት (Special Dulet).jpg" },
  { id: "item-86", name: "Enkulal Besega (እንቁላል በሥጋ)", price: 350, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Eggs scrambled with meat and traditional spices", isAvailable: true, preparationTime: 12, variants: [], extras: [], image: "/images/Yefseg/kurs/እንቁላል በሥጋ (Enkulal be Sega ).jpg" },
  { id: "item-87", name: "Yefyel Senber 1/4 kg (የፍየል ሰንበር 1/4 ኪሎ)", price: 500, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Quarter kilo of raw goat meat seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የፍየል ሰንበር (Yefeyel Senber).jpg" },
  { id: "item-88", name: "Yefyel Senber 1/2 kg (የፍየል ሰንበር 1/2 ኪሎ)", price: 1000, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Half kilo of raw goat meat seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የፍየል ሰንበር (Yefeyel Senber).jpg" },
  { id: "item-89", name: "Yefyel Senber 1 kg (የፍየል ሰንበር 1 ኪሎ)", price: 2000, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "One kilo of raw goat meat seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የፍየል ሰንበር (Yefeyel Senber).jpg" },
  { id: "item-90", name: "Yebere Senber 1/4 kg (የበሬ ሰንበር 1/4 ኪሎ)", price: 400, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Quarter kilo of raw beef seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የበሬ ሰንበር (Yebere Senber).jpg" },
  { id: "item-91", name: "Yebere Senber 1/2 kg (የበሬ ሰንበር 1/2 ኪሎ)", price: 800, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "Half kilo of raw beef seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የበሬ ሰንበር (Yebere Senber).jpg" },
  { id: "item-92", name: "Yebere Senber 1 kg (የበሬ ሰንበር 1 ኪሎ)", price: 1600, categoryId: "yefsig-breakfast", category: { id: "yefsig-breakfast", name: "ቁርስ (Breakfast)" }, description: "One kilo of raw beef seasoned with mitmita", isAvailable: true, preparationTime: 5, variants: [], extras: [], requiresButcher: true, image: "/images/Yefseg/kurs/የበሬ ሰንበር (Yebere Senber).jpg" },

  // Custom Fish items (ዓሳ)
  { id: "item-73", name: "Fish Lebleb (አሳ ለብለብ)", price: 600, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Fish lebleb prepared with traditional spices", isAvailable: true, preparationTime: 20, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ለብለብ (Fish Lebleb).jpg" },
  { id: "item-74", name: "Fish Dulet (አሳ ዱለት)", price: 600, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Minced fish sautéed with onions, peppers and herbs", isAvailable: true, preparationTime: 15, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ዱለት (Fish Dulet).jpg" },
  { id: "item-75", name: "Fish Goulash (አሳ ጉላሽ)", price: 800, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Fish goulash in rich tomato and herb sauce", isAvailable: true, preparationTime: 22, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ጉላሽ (Fish Goulash).jpg" },
  { id: "item-76", name: "Asa Koroso (አሳ ኮሮሶ)", price: 1000, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Whole fried fish seasoned with Ethiopian spices", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ኮሮሶ (Asa Koroso ).jpg" },
  { id: "item-77", name: "Asa Shekla half (አሳ ሸክላ ግማሽ)", price: 1000, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Half portion of fish shekla served sizzling in a clay pot", isAvailable: true, preparationTime: 25, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ሸክላ ግማሽ (Asa Shekla half).jpg" },
  { id: "item-78", name: "Asa Shekla full (አሳ ሸክላ ሙሉ)", price: 2000, categoryId: "yetsom-asa", category: { id: "yetsom-asa", name: "ዓሳ (Fish)" }, description: "Full portion of fish shekla served sizzling in a clay pot", isAvailable: true, preparationTime: 30, variants: [], extras: [], image: "/images/Yetsom/Fish/አሳ ሸክላ ግማሽ (Asa Shekla half).jpg" },
];

export async function ensureDemoItemsSeeded() {
  const persisted = await readDemoJSON<any>(".demo-menu-items.json");
  const deletedIds = await readDemoJSON<string[]>(".demo-deleted-items.json");
  const deletedSet = new Set(deletedIds);
  const hcIndex = new Map(demoItems.map((di: any) => [di.id, di]));
  const persistedIds = new Set(persisted.map((pi: any) => pi.id));

  // Find hardcoded items that are missing from persisted (not deleted)
  const missing = demoItems.filter((di: any) => !persistedIds.has(di.id) && !deletedSet.has(di.id));

  if (persisted.length === 0) {
    // First-time seed: write all hardcoded items
    await writeDemoJSON(".demo-menu-items.json", demoItems.filter((di: any) => !deletedSet.has(di.id)));
  } else if (missing.length > 0) {
    // Add-only: merge missing hardcoded items into persisted, preserving existing user data
    const userItems = persisted.filter((pi: any) => !hcIndex.has(pi.id));
    const nonDeletedHardcoded = demoItems.filter((di: any) => !deletedSet.has(di.id)).map((hc) => {
      const existing = persisted.find((p: any) => p.id === hc.id);
      return existing || hc;
    });
    await writeDemoJSON(".demo-menu-items.json", [...nonDeletedHardcoded, ...userItems]);
  }
}
